### ISSUE TITLE
Add wiki section that lists all related publications

### ISSUE THREAD

**Issue by hpl002** [bptlab/scylla#46]
Hi!

Just stumbled over your repository after glossing over [Automated discovery of business process simulation models from event logs](https://www.sciencedirect.com/science/article/pii/S0167923620300397#bb0030).

For external users it would be great if you could list any and all publications that are directly related to this project.

Thus far, i have found [Design of an Extensible BPMN Process Simulator](https://www.researchgate.net/publication/322524759_Design_of_an_Extensible_BPMN_Process_Simulator), but there might be more?

Looking forward to taking a deep dive in your work, so far i am very impressed!

Best regards,

Herman

**Comment by hpl002** [comment]
Currently tracking related works here. Will create PR once more have been located.
1. https://link.springer.com/chapter/10.1007%2F978-3-319-74030-0_62

**Comment by LeonBein** [comment]
Hi Herman! 
Nice to hear that you are interested in this project. 
I fear that there are few publications that directly talk about the architecture and design of the project (which I assume would help you most). I will still ask around and collect the results.
Best Regards,
Leon

**Comment by hpl002** [comment]
Hi Leon!

Managed to get i contact with Tsun Yin Wong directly after not finding his thesis online. Tsun  has written the following work:   
Wong, T.Y.: Extensible BPMN Process Simulator. Master’s thesis, Hasso Plattner Institut, University of Potsdam (2017).

From what i understand he was the originator of this project and his thesis could therefore be understood as the primary documentation.

From what i remember, i also think i found mentions of this project in a doctorate dissertation. I will add more works if and when they are discovered.

**Comment by LeonBein** [comment]
Yes! 
Tsun originally wrote this tool for his master's thesis, if you have access to it, it might be a very good starting point.
The dissertation you found might be [the one of](https://publishup.uni-potsdam.de/opus4-ubp/frontdoor/deliver/index/docId/40801/file/pufahl_diss.pdf) @LuisePufahl on batch activities?

**Comment by hpl002** [comment]
> Yes!
> Tsun originally wrote this tool for his master's thesis, if you have access to it, it might be a very good starting point.
> The dissertation you found might be [the one of](https://publishup.uni-potsdam.de/opus4-ubp/frontdoor/deliver/index/docId/40801/file/pufahl_diss.pdf) @LuisePufahl on batch activities?

That looks correct!

**Comment by hpl002** [comment]
Have there been any significant advancements or changes in the project from that which was originally written by Tsun? 

If so, would it be possible to maybe write up a small changelog? 😬

**Comment by LeonBein** [comment]
I think some of the bigger advancement are
a) Adding a UI, which aims to simplify configuring and running simulations
b) Various new plugins (which means new supported bpmn concepts), such as event-based gateways. Most prominently the batch activity plugin which we developed for Luise's research
c) More advanced plugin loading, which allows e.g. to load plugins from external Jars

**Comment by LeonBein** [comment]
Regarding related work: There is at least [another paper](https://www.sciencedirect.com/science/article/abs/pii/S0306437920301071?via%3Dihub) about batch activities that uses Scylla.

**Comment by hpl002** [comment]
Great. 

Have you had a look at the [bpSIM specification](https://www.bpsim.org/)? Thinking that might be a good way of making the simulator configurable.

The simulator input would then be a file conforming to the bpSIM specification. This file can then be created by a UI, a external system, etc. 

The simulator would then parse the file into its own internal configuration. 

Have not researched the extensibility of the specification yet. Assuming it is up to date with the latest BPMN release as it was published in 2014 and bpSIM was published in 2016.

**Comment by LeonBein** [comment]
Are wiki PRs possible? I found the following: https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github which states that they are not. The thread suggests to put the wiki repo into the main repo and then automate exchange between the repos - not sure if this is a good approach though ...

**Comment by hpl002** [comment]
Aha! I simply assumed that wiki PRs were possible, sorry about that.

Any wiki updates by third parties (such as myself) can be submitted as issues and tagged accordingly. Then whenever you or other project maintainers have the chance you can have a look at them.

Have not been able to have a proper look at the project yet so this is still pending. Will have a thorough rundown in the next couple of days and submit relevant updates/issues.
