### ISSUE TITLE
Default Timetables do not work as intended

### ISSUE THREAD

**Issue by MaximilianKoenig** [bptlab/scylla#72]
In a global configuration
with resource instances that have a default timetable assigned to them,
they are not simulated to work according to the timetable,
but rather work 24/7.

(Non-minimal) example: [Default_Timetables_Config.zip](https://github.com/bptlab/scylla/files/14101161/Default_Timetables_Config.zip)

In the example, all resource instances that have the "Day_Shift" assigned to them as "default timetable" work 24/7. If instead the "Day_Shift" is explicitly assigned to them, they work only during the intended times.

**Comment by LeonBein** [comment]
In https://github.com/bptlab/scylla/blob/9739a18b7c5f6494897457190a91f39d26da2de8/src/main/java/de/hpi/bpt/scylla/parser/GlobalConfigurationParser.java#L163-L165, only defined timetables are set. If no instance timetable is defined, it should fall back to the default on, as in https://github.com/bptlab/scylla/blob/9739a18b7c5f6494897457190a91f39d26da2de8/src/main/java/de/hpi/bpt/scylla/parser/GlobalConfigurationParser.java#L130-L132
